[google_service_account]
type = "service_account"
project_id = "rsct-rater-auth"
private_key_id = "219d7cb08eb222e96c4b585bcc5faacac0118555"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEv...ABC123
-----END PRIVATE KEY-----"""
client_email = "rsct-therapist-client@rsct-rater-auth.iam.gserviceaccount.com"
client_id = "114824133444244325487"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/rsct-therapist-client@rsct-rater-auth.iam.gserviceaccount.com"
